### ISSUE TITLE
Firefox 112+ shows double minimize/maximize/close buttons

### ISSUE THREAD

**Issue by fulalas** [lah7/gtk3-mushrooms#102]
gtk3-classic:
![classic](https://github.com/lah7/gtk3-classic/assets/27843666/75fa3b6d-4234-441d-b2aa-24c1ef7934c8)

gtk3 original:
![original](https://github.com/lah7/gtk3-classic/assets/27843666/0e56a894-cdc5-499f-8220-79199c24114e)

I know there's a [Firefox css tweak](https://forum.porteus.org/viewtopic.php?p=95125#p95125), but still...

**Comment by lah7** [comment]
I believe this is expected behaviour, similar to #32. Firefox _probably_ renders these controls in a way that GTK 3 can't patch. There are 2 solutions:

1. Tell Firefox to use the window title bar by right clicking the tab bar → "Customise Toolbar..." and then checking  "Title Bar" in the bottom-left:

    ![Screenshot_20230809_205805](https://github.com/lah7/gtk3-classic/assets/13032135/7236adc6-4d6d-4b69-b2ad-2e2702487d6f)

2. Otherwise, the patched GTK can use the original behaviour (show CSDs) by adding `GTK_CSD=0` to the start of the command in the desktop launcher for Firefox, depending on your desktop environment. For example:

       GTK_CSD=0 /usr/lib/firefox/firefox %u

**Comment by fulalas** [comment]
I see. Does @ZaWertun [repository](https://github.com/ZaWertun/gtk3-nocsd) still fix this issue?

**Comment by lah7** [comment]
Checked it out of curiously. Yes, that works too (against regular GTK 3), but it's essentially **solution 1** above by forcing the title bar (with the checkbox disappearing)

| gtk3 (title bar off, default) | gtk3 (title bar on) | gtk3-nocsd  (title bar forced on)|
| --| -- |--|
| ![Screenshot_20230811_215603](https://github.com/lah7/gtk3-classic/assets/13032135/feb59b67-fccb-4057-b083-40f50c5ab32d) | ![Screenshot_20230811_215606](https://github.com/lah7/gtk3-classic/assets/13032135/35572743-1288-4388-bd49-092bbfafb36a) | ![Screenshot_20230811_215548](https://github.com/lah7/gtk3-classic/assets/13032135/cd9c17cc-b602-466e-b2d1-7f6042f6a318) |

In contrast, `gtk3-classic`  shows the window borders regardless of what the application says (hence double controls), so checking "Title Bar" would be the easiest fix.

| gtk3-classic (default) | gtk3-classic (title bar on) | gtk3-classic (GTK_CSD=0) | gtk3-classic (GTK_CSD=1)
| --- | --- | --- | -- |
| ![Screenshot_20230811_220401](https://github.com/lah7/gtk3-classic/assets/13032135/c23b41d9-0916-4528-8d61-304580890573) | ![Screenshot_20230811_220408](https://github.com/lah7/gtk3-classic/assets/13032135/eb66230c-94cb-4e94-a384-ed157b0692a3) | ![Screenshot_20230811_220625](https://github.com/lah7/gtk3-classic/assets/13032135/702cc873-7721-47f8-8410-effc34babcf9) | ![Screenshot_20230811_221651](https://github.com/lah7/gtk3-classic/assets/13032135/7bb0d105-a362-42ab-beac-fc4cbdb6cd67)

Turns out that Firefox recognises `GTK_CSD=0` in their code which forces the title bar on (like `gtk3-nocsd`), even under normal `gtk3`. So, if you really wanted the default behaviour under `gtk3-classic`, you'd actually set it to `GTK_CSD=1` (or anything not `0`)

**Comment by fulalas** [comment]
Awesome! Thanks a lot! :)
