### ISSUE TITLE
Package will not build w/o atk

### ISSUE THREAD

**Issue by cassafrass387** [lah7/gtk3-mushrooms#110]
After removing atk (and at-spi2-core) from the PKGBUILD, and adding -D atk_bridge=false, the package will not build and continues checking for an atk dependency:
`makepkg -sir
...
Run-time dependency atk found: NO`
I haven't tried with any other system so unsure if the problem is specifically Arch-related, is universal, or is just something I've done wrong. 
My meson build command:
`arch-meson gtk+$_gtkver build ... -D atk_bridge=false ...`
Apologies for not simply uploading my PKGBUILD and the poor formating, I'm not home currently and I don't have a GUI on my laptop yet. 
Thanks!

**Comment by cassafrass387** [comment]
Nevermind, found patches from Kiss Linux to fully remove ATK. Doesn't matter too much anyways as I realized I'd have to patch almost every application which uses gtk to exclude atk.

**Comment by lah7** [comment]
No worries. Supposedly we _should_ [support building with ATK](https://github.com/lah7/gtk3-classic?tab=readme-ov-file#build-time) but it looks like some additional steps are needed first.

I see that those [Kiss Linux patches](https://github.com/kisslinux/repo/blob/602563a68f03dea73c7fcb827fc6716e8992c2f9/extra/gtk%2B3/build) are removing some stuff from `meson.build` since it seems the build system is forced to check for that dependency even though it's not needed.

I didn't spend long on this, but here's a diff of the PKGBUILD for any one who wants to pick it up:

```diff
--- PKGBUILD.a  2024-05-07 16:33:54.060628344 +0000
+++ PKGBUILD    2024-05-07 17:01:21.190896188 +0000
@@ -22,8 +22,6 @@
 arch=(x86_64)
 license=(LGPL-2.0-only)
 depends=(
-       at-spi2-atk
-       atk
        cairo
        desktop-file-utils
        fribidi
@@ -52,8 +50,6 @@
 
 makedepends=(
        adwaita-icon-theme
-       at-spi2-atk
-       atk
        cairo
        cantarell-fonts
        desktop-file-utils
@@ -109,12 +105,21 @@
 {
        CFLAGS+=" -DG_DISABLE_CAST_CHECKS"
 
+        # Remove references ATK from meson.build  - INCOMPLETE
+        sed -i 's/^  atkbridge_dep/#  atkbridge_dep/' gtk+-$_gtkver/meson.build
+        sed -i 's/^atk_pkgs =/atk_pkgs = [] # /' gtk+-$_gtkver/meson.build
+        sed -i "s/atkbridge_dep  = dependency('atk-bridge-2.0', version: at_spi2_atk_req)/#atkbridge_dep  = dependency('atk-bridge-2.0', version: at_spi2_atk_req)/g" gtk+-$_gtkver/meson.build
+        sed -i "/^\s*atk_pkgs += \['atk-bridge-2.0'\]/d" gtk+-$_gtkver/meson.build
+        sed -i "/^\s*atk_dep/d" gtk+-$_gtkver/meson.build
+        sed -i "/^\s*fallback \: \['atk'/d" gtk+-$_gtkver/meson.build
+
        # 64-bit
        arch-meson gtk+-$_gtkver build \
                -D broadway_backend=true \
                -D colord=auto \
                -D demos=false \
                -D examples=false \
+                -D atk_bridge=false \
                -D introspection=true \
                -D tests=false \
                -D installed_tests=false
```

This alone isn't enough, I imagine it can be improved with better use of `sed` commands:

    gtk+-3.24.41/gtk/meson.build:848:2: ERROR: Unknown variable "atk_dep".

I'll update the README for any others passing by.

Suppose the build _might_ succeed if `atk` related packages are installed at build time, then uninstalled afterwards.

**Comment by lah7** [comment]
This works, if the ATK packages are used as a build dependency only:

```diff
--- PKGBUILD.a  2024-05-07 17:22:19.530151126 +0000
+++ PKGBUILD.b  2024-05-07 17:22:09.333285484 +0000
@@ -22,8 +22,6 @@
 arch=(x86_64)
 license=(LGPL-2.0-only)
 depends=(
-       at-spi2-atk
-       atk
        cairo
        desktop-file-utils
        fribidi
@@ -116,6 +114,7 @@
                -D demos=false \
                -D examples=false \
                -D introspection=true \
+                -D atk_bridge=false \
                -D tests=false \
                -D installed_tests=false
        ninja -C build
```
