### ISSUE TITLE
CSD appears in XFCE windows despite `unset GTK_CSD`

### ISSUE THREAD

**Issue by Flashwalker** [lah7/gtk3-mushrooms#96]
Don't know bug or feature
CSD panel appears in XFCE windows despite `unset GTK_CSD` with ppa:lah7/gtk3-classic https://github.com/lah7/gtk3-classic/discussions/92

![image](https://user-images.githubusercontent.com/2188215/222867970-29ede2ed-3b6f-4a28-9d56-076e82d2c654.png)

If purge the ppa and packages:
```
gir1.2-gtk-3.0 gtk-update-icon-cache libgail-3-0 libgtk-3-0 libgtk-3-bin libgtk-3-common libgtk-3-dev

```

That CSD panel in Xfce windows has disappeared because it now uses (or does not use) its own window border. So, now CSD substitutes the window manager's window border
![image](https://user-images.githubusercontent.com/2188215/225221119-0923238e-00dd-461f-8103-3d63ffd91c4f.png)
(close, minimize, maximize buttons are just hidden by custom gtk.css)

**Comment by lah7** [comment]
What distro/release are you using?

If I recall, some CSD patches were excluded for the Ubuntu packages because that "double controls" issue was a problem under Ubuntu MATE.

**Comment by Flashwalker** [comment]
> What distro/release are you using?

I'm using Ubuntu 22.04

**Comment by robson-66** [comment]
I think it depends a lot on the GTK theme.
For example, for me on Xfce4 it looks like this

![ScreenShot](https://i.postimg.cc/PJCSqq6x/Przechwycenie-obrazu-ekranu-2023-04-04-21-11-56.png")

And give it a try with this theme https://github.com/robson-66/DarkCold

**Comment by Flashwalker** [comment]
> And give it a try with this theme https://github.com/robson-66/DarkCold

Noup
![image](https://user-images.githubusercontent.com/2188215/229982729-b62b1f6b-4c7f-4bef-895e-ca8c3043f97d.png)

**Comment by robson-66** [comment]
This first screenshot of mine was made on a compiz session, and this is what it looks like on an xfwm4 session 

![ScreenShot](https://i.postimg.cc/BbcSgVXf/Przechwycenie-obrazu-ekranu-2023-04-05-13-01-24.png)

There is a big difference between your screenshot and mine.

**Comment by robson-66** [comment]
What patches are you building the `gtk3-classic` package with? because I'm only with them

```
	appearance__buttons-menus-icons.patch
	appearance__disable-backdrop.patch
	appearance__file-chooser.patch
	appearance__message-dialogs.patch
	appearance__print-dialog.patch
	appearance__smaller-statusbar.patch
	csd__clean-headerbar.patch
	csd__disabled-by-default.patch
	csd__server-side-shadow.patch
	file-chooser__places-sidebar.patch
	file-chooser__typeahead.patch
	fixes__labels-wrapping.patch
	fixes__too-large-menu-covers-bar.disabled-patch
	other__hide-insert-emoji.patch
	other__mnemonics-delay.patch
	other__remove_dead_keys_underline.patch
	popovers__color-chooser.patch
	popovers__file-chooser-list.patch
	popovers__places-sidebar.patch
	notebook_wheel_scroll.patch
	treeview__alternating_row_colours.patch
	window__rgba-visual.patch

```

**Comment by Flashwalker** [comment]
> What patches are you building the `gtk3-classic` package with? because I'm only with them

I'm just using packages from ppa

**Comment by lah7** [comment]
I believe it's a problem specific to the Ubuntu package. I'll need to review it and repackage when I get time.

@robson-66 I'm guessing you're **not** using Ubuntu 22.04? (Likely, _"building"_ on Arch?)

**Comment by robson-66** [comment]
Yes, I'm on Arch Linux.

**Comment by mochaaP** [comment]
I think you might need to set `/Gtk/DialogsUseHeader` to `false`: <https://gitlab.xfce.org/xfce/libxfce4ui/-/issues/14>

**Comment by Flashwalker** [comment]
> I think you might need to set `/Gtk/DialogsUseHeader` to `false`: https://gitlab.xfce.org/xfce/libxfce4ui/-/issues/14

I'm allredy have
```
$ xfconf-query -c xsettings -p /Gtk/DialogsUseHeader
false

```
it's not related

**Comment by lah7** [comment]
I wondered if this is still an issue and yes, I can see it on Ubuntu 22.04 (XFCE 4.16), but not under Arch Linux (XFCE 4.18).

A quick web search revealed articles that XFCE 4.16 switched to CSD by default. Later, I found [XFCE's blog](https://blog.xfce.org/) post for "Xfce 4.18 released" (December 15, 2022) which implies that they went back to server side decorations. 👍🏼 

> All header bars of Xfce Windows/Dialogs by default will be drawn by the window manager now (Xfwm4).

In terms of `gtk3-classic`, I don't see what we can do. Our patches make the CSD act more like a toolbar (like removing the center window title & right window buttons) but these XFCE apps still have an item (or two) in the CSD area, like the search button.

In the original post, that screenshot shows a very thick CSD, so that might be theme related.

![Screenshot_20230804_185119](https://github.com/lah7/gtk3-classic/assets/13032135/3b10d3d1-0944-4008-8234-1dc5dbdd6c3a)

![Screenshot_20230804_184735](https://github.com/lah7/gtk3-classic/assets/13032135/57cb19ee-37c0-4ed9-ae20-70f45146e0cb)

_Left = Normal | Right = Patched_

The better solution is to upgrade XFCE, but that might not be feasible under Ubuntu 22.04.

**Comment by Flashwalker** [comment]
> "Xfce 4.18 released" (December 15, 2022) which implies that they went back to server side decorations. 👍🏼
> 
Yeah, it's ok now with 4.18

![2023-08-05_02-16-15](https://github.com/lah7/gtk3-classic/assets/2188215/8e7dc6cc-3940-4fe5-afb5-deecda410acc)
